import { Player } from './types';

export const players: Player[] = [
  {
    "id": "sunil-narine",
    "name": "Sunil Narine",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.4,
    "maxPrice": 40,
    "rating": 100,
    "popularity": 56,
    "isCapped": true
  },
  {
    "id": "virat-kohli",
    "name": "Virat Kohli",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.4,
    "maxPrice": 40,
    "rating": 94,
    "popularity": 27,
    "isCapped": true
  },
  {
    "id": "tristan-stubbs",
    "name": "Tristan Stubbs",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.4,
    "maxPrice": 40,
    "rating": 86,
    "popularity": 21,
    "isCapped": true
  },
  {
    "id": "devon-conway",
    "name": "Devon Conway",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.2,
    "maxPrice": 30,
    "rating": 76,
    "popularity": 21,
    "isCapped": true
  },
  {
    "id": "andre-russell",
    "name": "Andre Russell",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.2,
    "maxPrice": 30,
    "rating": 74,
    "popularity": 50,
    "isCapped": true
  },
  {
    "id": "shashank-singh",
    "name": "Shashank Singh",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.2,
    "maxPrice": 30,
    "rating": 72,
    "popularity": 16,
    "isCapped": true
  },
  {
    "id": "ruturaj-gaikwad",
    "name": "Ruturaj Gaikwad",
    "role": "All-rounder",
    "basePrice": 2,
    "minPrice": 1.2,
    "maxPrice": 30,
    "rating": 71,
    "popularity": 24,
    "isCapped": true
  },
  {
    "id": "travis-head",
    "name": "Travis Head",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 69,
    "popularity": 24,
    "isCapped": false
  },
  {
    "id": "riyan-parag",
    "name": "Riyan Parag",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 68,
    "popularity": 19,
    "isCapped": false
  },
  {
    "id": "sam-curran",
    "name": "Sam Curran",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 66,
    "popularity": 44,
    "isCapped": false
  },
  {
    "id": "abhishek-sharma",
    "name": "Abhishek Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 65,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "jasprit-bumrah",
    "name": "Jasprit Bumrah",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 65,
    "popularity": 57,
    "isCapped": false
  },
  {
    "id": "jofra-archer",
    "name": "Jofra Archer",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 65,
    "popularity": 49,
    "isCapped": false
  },
  {
    "id": "harshal-patel",
    "name": "Harshal Patel",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 64,
    "popularity": 47,
    "isCapped": false
  },
  {
    "id": "sanju-samson",
    "name": "Sanju Samson",
    "role": "Wicket-keeper Batsman",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 64,
    "popularity": 18,
    "isCapped": false
  },
  {
    "id": "nicholas-pooran",
    "name": "Nicholas Pooran",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 63,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "marcus-stoinis",
    "name": "Marcus Stoinis",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.6,
    "maxPrice": 15,
    "rating": 61,
    "popularity": 28,
    "isCapped": false
  },
  {
    "id": "axar-patel",
    "name": "Axar Patel",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 60,
    "popularity": 34,
    "isCapped": false
  },
  {
    "id": "pat-cummins",
    "name": "Pat Cummins",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 60,
    "popularity": 47,
    "isCapped": false
  },
  {
    "id": "shivam-dube",
    "name": "Shivam Dube",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 59,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "varun-chakaravarthy",
    "name": "Varun Chakaravarthy",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 59,
    "popularity": 48,
    "isCapped": false
  },
  {
    "id": "arshdeep-singh",
    "name": "Arshdeep Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 58,
    "popularity": 45,
    "isCapped": false
  },
  {
    "id": "heinrich-klaasen",
    "name": "Heinrich Klaasen",
    "role": "Wicket-keeper Batsman",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 58,
    "popularity": 18,
    "isCapped": false
  },
  {
    "id": "kl-rahul",
    "name": "KL Rahul",
    "role": "Wicket-keeper Batsman",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 58,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "t-natarajan",
    "name": "T Natarajan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 58,
    "popularity": 45,
    "isCapped": false
  },
  {
    "id": "avesh-khan",
    "name": "Avesh Khan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 57,
    "popularity": 46,
    "isCapped": false
  },
  {
    "id": "mitchell-starc",
    "name": "Mitchell Starc",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 56,
    "popularity": 41,
    "isCapped": false
  },
  {
    "id": "b-sai-sudharsan",
    "name": "B. Sai Sudharsan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 55,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "phil-salt",
    "name": "Phil Salt",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 55,
    "popularity": 15,
    "isCapped": false
  },
  {
    "id": "rishabh-pant",
    "name": "Rishabh Pant",
    "role": "Wicket-keeper Batsman",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 55,
    "popularity": 15,
    "isCapped": false
  },
  {
    "id": "harshit-rana",
    "name": "Harshit Rana",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 54,
    "popularity": 45,
    "isCapped": false
  },
  {
    "id": "mohammad-shami",
    "name": "Mohammad Shami",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 54,
    "popularity": 45,
    "isCapped": false
  },
  {
    "id": "prasidh-krishna",
    "name": "Prasidh Krishna",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 54,
    "popularity": 47,
    "isCapped": false
  },
  {
    "id": "tushar-deshpande",
    "name": "Tushar Deshpande",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 54,
    "popularity": 41,
    "isCapped": false
  },
  {
    "id": "kuldeep-yadav",
    "name": "Kuldeep Yadav",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 53,
    "popularity": 38,
    "isCapped": false
  },
  {
    "id": "ravindra-jadeja",
    "name": "Ravindra Jadeja",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 52,
    "popularity": 28,
    "isCapped": false
  },
  {
    "id": "yuzvendra-chahal",
    "name": "Yuzvendra Chahal",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 52,
    "popularity": 44,
    "isCapped": false
  },
  {
    "id": "rajat-patidar",
    "name": "Rajat Patidar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 50,
    "popularity": 15,
    "isCapped": false
  },
  {
    "id": "venkatesh-iyer",
    "name": "Venkatesh Iyer",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 50,
    "popularity": 15,
    "isCapped": false
  },
  {
    "id": "faf-du-plessis",
    "name": "Faf du Plessis",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 49,
    "popularity": 16,
    "isCapped": false
  },
  {
    "id": "n-tilak-varma",
    "name": "N. Tilak Varma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 49,
    "popularity": 15,
    "isCapped": false
  },
  {
    "id": "sandeep-sharma",
    "name": "Sandeep Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 49,
    "popularity": 42,
    "isCapped": false
  },
  {
    "id": "trent-boult",
    "name": "Trent Boult",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 49,
    "popularity": 40,
    "isCapped": false
  },
  {
    "id": "khaleel-ahmed",
    "name": "Khaleel Ahmed",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 48,
    "popularity": 41,
    "isCapped": false
  },
  {
    "id": "mukesh-kumar",
    "name": "Mukesh Kumar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 48,
    "popularity": 39,
    "isCapped": false
  },
  {
    "id": "suryakumar-yadav",
    "name": "Suryakumar Yadav",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 48,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "matheesha-pathirana",
    "name": "Matheesha Pathirana",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 47,
    "popularity": 29,
    "isCapped": false
  },
  {
    "id": "mohammed-siraj",
    "name": "Mohammed Siraj",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 47,
    "popularity": 37,
    "isCapped": false
  },
  {
    "id": "shubman-gill",
    "name": "Shubman Gill",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 47,
    "popularity": 20,
    "isCapped": false
  },
  {
    "id": "hardik-pandya",
    "name": "Hardik Pandya",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 46,
    "popularity": 33,
    "isCapped": false
  },
  {
    "id": "jake-fraser-mcgurk",
    "name": "Jake Fraser-McGurk",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 46,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "jos-buttler",
    "name": "Jos Buttler",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 46,
    "popularity": 23,
    "isCapped": false
  },
  {
    "id": "yashasvi-jaiswal",
    "name": "Yashasvi Jaiswal",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 46,
    "popularity": 21,
    "isCapped": false
  },
  {
    "id": "gerald-coetzee",
    "name": "Gerald Coetzee",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 45,
    "popularity": 31,
    "isCapped": false
  },
  {
    "id": "nitish-kumar-reddy",
    "name": "Nitish Kumar Reddy",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 45,
    "popularity": 19,
    "isCapped": false
  },
  {
    "id": "rohit-sharma",
    "name": "Rohit Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 45,
    "popularity": 20,
    "isCapped": false
  },
  {
    "id": "yash-dayal",
    "name": "Yash Dayal",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 45,
    "popularity": 37,
    "isCapped": false
  },
  {
    "id": "shahbaz-ahamad",
    "name": "Shahbaz Ahamad",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 43,
    "popularity": 26,
    "isCapped": false
  },
  {
    "id": "will-jacks",
    "name": "Will Jacks",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 42,
    "popularity": 18,
    "isCapped": false
  },
  {
    "id": "yash-thakur",
    "name": "Yash Thakur",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 42,
    "popularity": 37,
    "isCapped": false
  },
  {
    "id": "shreyas-iyer",
    "name": "Shreyas Iyer",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.5,
    "maxPrice": 12,
    "rating": 41,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "mohit-sharma",
    "name": "Mohit Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 40,
    "popularity": 32,
    "isCapped": false
  },
  {
    "id": "rashid-khan",
    "name": "Rashid Khan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 40,
    "popularity": 28,
    "isCapped": false
  },
  {
    "id": "kagiso-rabada",
    "name": "Kagiso Rabada",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 39,
    "popularity": 28,
    "isCapped": false
  },
  {
    "id": "bhuvneshwar-kumar",
    "name": "Bhuvneshwar Kumar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 37,
    "popularity": 30,
    "isCapped": false
  },
  {
    "id": "ravichandran-ashwin",
    "name": "Ravichandran Ashwin",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 37,
    "popularity": 27,
    "isCapped": false
  },
  {
    "id": "sai-kishore",
    "name": "Sai Kishore",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 37,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "harpreet-brar",
    "name": "Harpreet Brar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 36,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "rahul-chahar",
    "name": "Rahul Chahar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 36,
    "popularity": 25,
    "isCapped": false
  },
  {
    "id": "ravi-bishnoi",
    "name": "Ravi Bishnoi",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 36,
    "popularity": 27,
    "isCapped": false
  },
  {
    "id": "abishek-porel",
    "name": "Abishek Porel",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 35,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "josh-hazlewood",
    "name": "Josh Hazlewood",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 35,
    "popularity": 27,
    "isCapped": false
  },
  {
    "id": "krunal-pandya",
    "name": "Krunal Pandya",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 35,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "mohsin-khan",
    "name": "Mohsin Khan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 35,
    "popularity": 25,
    "isCapped": false
  },
  {
    "id": "vaibhav-arora",
    "name": "Vaibhav Arora",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 35,
    "popularity": 27,
    "isCapped": false
  },
  {
    "id": "ishant-sharma",
    "name": "Ishant Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 33,
    "popularity": 25,
    "isCapped": false
  },
  {
    "id": "karn-sharma",
    "name": "Karn Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 33,
    "popularity": 19,
    "isCapped": false
  },
  {
    "id": "prabhsimran-singh",
    "name": "Prabhsimran Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 33,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "rachin-ravindra",
    "name": "Rachin Ravindra",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 33,
    "popularity": 9,
    "isCapped": false
  },
  {
    "id": "ishan-kishan",
    "name": "Ishan Kishan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 32,
    "popularity": 13,
    "isCapped": false
  },
  {
    "id": "ayush-badoni",
    "name": "Ayush Badoni",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "dhruv-jurel",
    "name": "Dhruv Jurel",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "glenn-maxwell",
    "name": "Glenn Maxwell",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 18,
    "isCapped": false
  },
  {
    "id": "lockie-ferguson",
    "name": "Lockie Ferguson",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "noor-ahmad",
    "name": "Noor Ahmad",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 21,
    "isCapped": false
  },
  {
    "id": "wanindu-hasaranga",
    "name": "Wanindu Hasaranga",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 31,
    "popularity": 23,
    "isCapped": false
  },
  {
    "id": "ms-dhoni",
    "name": "MS Dhoni",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 30,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "mayank-yadav",
    "name": "Mayank Yadav",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 30,
    "popularity": 16,
    "isCapped": false
  },
  {
    "id": "quinton-de-kock",
    "name": "Quinton de Kock",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 30,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "rasikh-dar",
    "name": "Rasikh Dar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 30,
    "popularity": 23,
    "isCapped": false
  },
  {
    "id": "swapnil-singh",
    "name": "Swapnil Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 30,
    "popularity": 16,
    "isCapped": false
  },
  {
    "id": "jaydev-unadkat",
    "name": "Jaydev Unadkat",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 29,
    "popularity": 22,
    "isCapped": false
  },
  {
    "id": "mayank-markande",
    "name": "Mayank Markande",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 27,
    "popularity": 20,
    "isCapped": false
  },
  {
    "id": "moeen-ali",
    "name": "Moeen Ali",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 27,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "nuwan-thushara",
    "name": "Nuwan Thushara",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 27,
    "popularity": 20,
    "isCapped": false
  },
  {
    "id": "ramandeep-singh",
    "name": "Ramandeep Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 26,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "aiden-markram",
    "name": "Aiden Markram",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 25,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "liam-livingstone",
    "name": "Liam Livingstone",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 25,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "tim-david",
    "name": "Tim David",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 25,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "abdul-samad",
    "name": "Abdul Samad",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 24,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "david-miller",
    "name": "David Miller",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 24,
    "popularity": 9,
    "isCapped": false
  },
  {
    "id": "kuldeep-sen",
    "name": "Kuldeep Sen",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 24,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "anrich-nortje",
    "name": "Anrich Nortje",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 23,
    "popularity": 17,
    "isCapped": false
  },
  {
    "id": "ashutosh-sharma",
    "name": "Ashutosh Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 23,
    "popularity": 9,
    "isCapped": false
  },
  {
    "id": "deepak-hooda",
    "name": "Deepak Hooda",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 23,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "jitesh-sharma",
    "name": "Jitesh Sharma",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 23,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "shahrukh-khan",
    "name": "Shahrukh Khan",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 23,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "darshan-nalkande",
    "name": "Darshan Nalkande",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 22,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "simarjeet-singh",
    "name": "Simarjeet Singh",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 22,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "angkrish-raghuvanshi",
    "name": "Angkrish Raghuvanshi",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "deepak-chahar",
    "name": "Deepak Chahar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "glenn-phillips",
    "name": "Glenn Phillips",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "kumar-kartikeya-singh",
    "name": "Kumar Kartikeya Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 14,
    "isCapped": false
  },
  {
    "id": "lungi-ngidi",
    "name": "Lungi Ngidi",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "naman-dhir",
    "name": "Naman Dhir",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "rahul-tewatia",
    "name": "Rahul Tewatia",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.4,
    "maxPrice": 8,
    "rating": 21,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "akash-singh",
    "name": "Akash Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 20,
    "popularity": 13,
    "isCapped": false
  },
  {
    "id": "azmatullah-omarzai",
    "name": "Azmatullah Omarzai",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 20,
    "popularity": 12,
    "isCapped": false
  },
  {
    "id": "rinku-singh",
    "name": "Rinku Singh",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 20,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "akash-madhwal",
    "name": "Akash Madhwal",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 19,
    "popularity": 13,
    "isCapped": false
  },
  {
    "id": "fazalhaq-farooqi",
    "name": "Fazalhaq Farooqi",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 19,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "mohd-arshad-khan",
    "name": "Mohd. Arshad Khan",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 19,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "vyshak-vijay-kumar",
    "name": "Vyshak Vijay Kumar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 19,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "ajinkya-rahane",
    "name": "Ajinkya Rahane",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 18,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "rahul-tripathi",
    "name": "Rahul Tripathi",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 18,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "romario-shepherd",
    "name": "Romario Shepherd",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 18,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "shreyas-gopal",
    "name": "Shreyas Gopal",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 18,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "spencer-johnson",
    "name": "Spencer Johnson",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 18,
    "popularity": 11,
    "isCapped": false
  },
  {
    "id": "mahipal-lomror",
    "name": "Mahipal Lomror",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 17,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "mujeeb-ur-rahman",
    "name": "Mujeeb Ur Rahman",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 17,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "rajvardhan-hangargekar",
    "name": "Rajvardhan Hangargekar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 17,
    "popularity": 7,
    "isCapped": false
  },
  {
    "id": "reece-topley",
    "name": "Reece Topley",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 17,
    "popularity": 10,
    "isCapped": false
  },
  {
    "id": "shimron-hetmyer",
    "name": "Shimron Hetmyer",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 17,
    "popularity": 8,
    "isCapped": false
  },
  {
    "id": "rovman-powell",
    "name": "Rovman Powell",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 16,
    "popularity": 7,
    "isCapped": false
  },
  {
    "id": "marco-jansen",
    "name": "Marco Jansen",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 15,
    "popularity": 4,
    "isCapped": false
  },
  {
    "id": "mitchell-santner",
    "name": "Mitchell Santner",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 15,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "nehal-wadhera",
    "name": "Nehal Wadhera",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 15,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "anshul-kamboj",
    "name": "Anshul Kamboj",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 14,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "maheesh-theekshana",
    "name": "Maheesh Theekshana",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 14,
    "popularity": 7,
    "isCapped": false
  },
  {
    "id": "pravin-dubey",
    "name": "Pravin Dubey",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 14,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "manish-pandey",
    "name": "Manish Pandey",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 13,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "mitchell-marsh",
    "name": "Mitchell Marsh",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 13,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "anuj-rawat",
    "name": "Anuj Rawat",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 12,
    "popularity": 4,
    "isCapped": false
  },
  {
    "id": "nathan-ellis",
    "name": "Nathan Ellis",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 12,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "rahmanullah-gurbaz",
    "name": "Rahmanullah Gurbaz",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 12,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "adam-zampa",
    "name": "Adam Zampa",
    "role": "Bowler",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 11,
    "popularity": 6,
    "isCapped": false
  },
  {
    "id": "vijay-shankar",
    "name": "Vijay Shankar",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 11,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "yudhvir-singh",
    "name": "Yudhvir Singh",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 11,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "m-siddharth",
    "name": "M Siddharth",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 10,
    "popularity": 4,
    "isCapped": false
  },
  {
    "id": "sameer-rizvi",
    "name": "Sameer Rizvi",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 10,
    "popularity": 5,
    "isCapped": false
  },
  {
    "id": "jayant-yadav",
    "name": "Jayant Yadav",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 9,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "kulwant-khejroliya",
    "name": "Kulwant Khejroliya",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 9,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "akash-deep",
    "name": "Akash Deep",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 8,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "atharva-taide",
    "name": "Atharva Taide",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 8,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "devdutt-padikkal",
    "name": "Devdutt Padikkal",
    "role": "All-rounder",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 8,
    "popularity": 4,
    "isCapped": false
  },
  {
    "id": "washington-sundar",
    "name": "Washington Sundar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 8,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "kamlesh-nagarkoti",
    "name": "Kamlesh Nagarkoti",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 7,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "kwena-maphaka",
    "name": "Kwena Maphaka",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 7,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "shubham-dubey",
    "name": "Shubham Dubey",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 7,
    "popularity": 3,
    "isCapped": false
  },
  {
    "id": "abhinav-manohar",
    "name": "Abhinav Manohar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 5,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "anukul-roy",
    "name": "Anukul Roy",
    "role": "Bowler",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 5,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "karun-nair",
    "name": "Karun Nair",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 5,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "suyash-sharma",
    "name": "Suyash Sharma",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 5,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "vishnu-vinod",
    "name": "Vishnu Vinod",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 5,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "arjun-tendulkar",
    "name": "Arjun Tendulkar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 4,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "donovan-ferreira",
    "name": "Donovan Ferreira",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 4,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "kumar-kushagra",
    "name": "Kumar Kushagra",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 4,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "nitish-rana",
    "name": "Nitish Rana",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 4,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "shamar-joseph",
    "name": "Shamar Joseph",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 4,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "arshin-kulkarni",
    "name": "Arshin Kulkarni",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 3,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "dushmantha-chameera",
    "name": "Dushmantha Chameera",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 3,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "manav-suthar",
    "name": "Manav Suthar",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 3,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "sherfane-rutherford",
    "name": "Sherfane Rutherford",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 3,
    "popularity": 2,
    "isCapped": false
  },
  {
    "id": "umran-malik",
    "name": "Umran Malik",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 3,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "mukesh-choudhary",
    "name": "Mukesh Choudhary",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 2,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "raj-angad-bawa",
    "name": "Raj Angad Bawa",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 2,
    "popularity": 1,
    "isCapped": false
  },
  {
    "id": "sachin-baby",
    "name": "Sachin Baby",
    "role": "Batsman",
    "basePrice": 1,
    "minPrice": 0.3,
    "maxPrice": 5,
    "rating": 1,
    "popularity": 1,
    "isCapped": false
  }
];
